name: aerospike-client-java

container:
  - base:
      - 192.168.106.181/build/aerospike-client-java:openjdk-6
      - 192.168.106.181/build/aerospike-client-java:openjdk-7
      - 192.168.106.181/build/aerospike-client-java:openjdk-8

build:
  - name: build
    script:
      - mvn clean
      - mvn install
      - mvn -f client/pom.xml javadoc:javadoc javadoc:jar
    artifact:
      - client/target/*.jar
